chore: change indent

diff --git a/get_nginx_config b/get_nginx_config
--- a/get_nginx_config
+++ b/get_nginx_config
@@ -3,22 +3,22 @@
 wget https://raw.githubusercontent.com/776A0A/tools/main/packed/nginx.zip
 
 if ! command -v unzip >/dev/null; then
-  echo "\033[33mUnzip tool is not installed.\033[0m"
-  read -p "Do you want to install it? (y/n) " choice
-  case "$choice" in
-  y | Y)
-    echo "Installing unzip tool..."
-    yum install -y unzip
-    ;;
-  n | N)
-    echo "Exiting script."
-    exit 1
-    ;;
-  *)
-    echo "Invalid choice. Exiting script."
-    exit 1
-    ;;
-  esac
+    echo "\033[33mUnzip tool is not installed.\033[0m"
+    read -p "Do you want to install it? (y/n) " choice
+    case "$choice" in
+    y | Y)
+        echo "Installing unzip tool..."
+        yum install -y unzip
+        ;;
+    n | N)
+        echo "Exiting script."
+        exit 1
+        ;;
+    *)
+        echo "Invalid choice. Exiting script."
+        exit 1
+        ;;
+    esac
 fi
 
 unzip nginx.zip
diff --git a/zip_it b/zip_it
--- a/zip_it
+++ b/zip_it
@@ -1,49 +1,49 @@
 #!/bin/bash
 
 if ! command -v zip >/dev/null; then
-  echo "\033[33mZip tool is not installed.\033[0m"
-  read -p "Do you want to install it? (y/n) " choice
-  case "$choice" in
-  y | Y)
-    echo "Installing zip tool..."
-    yum install -y zip
-    ;;
-  n | N)
-    echo "Exiting script."
-    exit 1
-    ;;
-  *)
-    echo "Invalid choice. Exiting script."
-    exit 1
-    ;;
-  esac
+    echo "\033[33mZip tool is not installed.\033[0m"
+    read -p "Do you want to install it? (y/n) " choice
+    case "$choice" in
+    y | Y)
+        echo "Installing zip tool..."
+        yum install -y zip
+        ;;
+    n | N)
+        echo "Exiting script."
+        exit 1
+        ;;
+    *)
+        echo "Invalid choice. Exiting script."
+        exit 1
+        ;;
+    esac
 fi
 
 if [ ! -d "packed" ]; then
-  mkdir "packed"
+    mkdir "packed"
 fi
 
 if [ $# -eq 0 ]; then
-  echo "Usage: zip_it <file/dir> [name]"
-  exit 1
+    echo "Usage: zip_it <file/dir> [name]"
+    exit 1
 fi
 
 if [ $# -eq 1 ]; then
-  name=$(basename "$1")
+    name=$(basename "$1")
 else
-  name="$2"
+    name="$2"
 fi
 
 if [ -d "$1" ]; then
-  zip -r "packed/$name.zip" "$1"
+    zip -r "packed/$name.zip" "$1"
 else
-  zip "packed/$name.zip" "$1"
+    zip "packed/$name.zip" "$1"
 fi
 
 if [ $? -eq 0 ]; then
-  echo -e "\033[32mFile compressed to packed/$name.zip\033[0m"
+    echo -e "\033[32mFile compressed to packed/$name.zip\033[0m"
 else
-  echo -e "\033[31mCompression failed.\033[0m"
+    echo -e "\033[31mCompression failed.\033[0m"
 fi
 
 exit 0
